[env:arduino_nano_esp32_remote]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

monitor_speed = 115200

extra_scripts = pre:extra_script.py

lib_deps = 
    olikraus/U8g2@^2.36.4